apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-4shh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-4shh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-4shh
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-4shh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-4shh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uqkm-tenant/rhtap-demo-app/hacbs-test-project-4shh@sha256:4f44315a252dd0e6a64cc584ea1516fc9164fb5279cdbcd426eb9928de87a87a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
